# Math387 Lab Assignment 2
## An experimental study of the growth factor for Gaussian elimination with partial pivoting. 
### Modified by Shenshun Yao; Student ID:260709204


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random as rn

## (1). Generating a random Matrix
Write a function that takes $n$ as its parameter and generates an $n*n$ matrix, whose entries are random numbers uniformly distributed in $[-1,1]$.

In order to simplify the calculation, we assume $n \in N^+$ and $n \in [1,100]$.

In [2]:
n=rn.randint(1,100)  
A=np.random.uniform(-1,1,(n,n))
print(n)
print(A)

42
[[ 0.84895089 -0.88721527 -0.5602413  ...,  0.68818138 -0.94789817
  -0.38172943]
 [-0.61529925  0.93609265  0.28847505 ..., -0.05312876  0.62817115
   0.67247973]
 [-0.45503973  0.60566135  0.13934135 ...,  0.24050922 -0.73042921
  -0.1305973 ]
 ..., 
 [-0.62732186  0.87297037 -0.09699509 ..., -0.30163411 -0.066924
   0.35217183]
 [-0.87263025  0.34967535  0.25735797 ...,  0.84290766  0.7165184
  -0.37959991]
 [-0.62032188  0.38950811 -0.81740023 ..., -0.73203763  0.43415682
  -0.03022189]]


## (2). Implement Gaussian elimination with partial pivoting

In [3]:
import numpy as np

def GEPP(A, b, doPricing = True):
    '''
    Gaussian elimination with partial pivoting:
    
    input: A is an n x n numpy matrix, b is an n x 1 numpy array
    output: x is the solution of Ax=b,
    
    with the entries permuted in accordance with the pivoting done by the GEPP algorithm.
    
    post-condition: A and b have been modified, A becomes an upper triangular matrix.
    '''
    n = len(A)
    if b.size != n:
        raise ValueError("Invalid argument: incompatible sizes between"+
                         "A & b.", b.size, n)
    # k represents the current pivot row. Since GE traverses the matrix in the 
    # upper right triangle, we also use k for indicating the k-th diagonal 
    # column index.
    
    # Elimination
    for k in range(n-1):
        if doPricing:
            # Pivot
            maxindex = abs(A[k:,k]).argmax() + k
            if A[maxindex, k] == 0:
                raise ValueError("Matrix is singular.")
            # Swap
            if maxindex != k:
                A[[k,maxindex]] = A[[maxindex, k]]
                b[[k,maxindex]] = b[[maxindex, k]]
        else:
            if A[k, k] == 0:
                raise ValueError("Pivot element is zero. Try setting doPricing to True.")
        #Eliminate
        for row in range(k+1, n):
            multiplier = A[row,k]/A[k,k]
            A[row, k:] = A[row, k:] - multiplier*A[k, k:]
            b[row] = b[row] - multiplier*b[k]
    # Back Substitution
    x = np.zeros(n)
    for k in range(n-1, -1, -1):
        x[k] = (b[k] - np.dot(A[k,k+1:],x[k+1:]))/A[k,k]
    return x

if __name__ == "__main__":
    A = np.array([[0.02,0.01,0.,-0.],[1.,2.,1.,0.],[0.,1.,2.,1.],[0.,0.,100.,200.]])
    b =  np.array([[0.02],[1.],[4.],[800.]])
    print (GEPP(A,b))
    print (A)
    print (b)
    

[ 1.  0.  0.  4.]
[[  1.00000000e+00   2.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   2.00000000e+00   1.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+02   2.00000000e+02]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00  -5.00000000e-02]]
[[  1.00000000e+00]
 [  4.00000000e+00]
 [  8.00000000e+02]
 [ -2.00000000e-01]]
